#Constraints únicos para nodos principales
CREATE CONSTRAINT IF NOT EXISTS FOR (e:Estudiante) REQUIRE e.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (m:Materia) REQUIRE m.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (p:Profesor) REQUIRE p.id IS UNIQUE;

